---
title: "Cue interactions 05-22[repeat study]"
author: "Sarah"
date: '2023-03-29'
output: html_document
---

# Cue interactions 05-2022  


loading packages 

```{r}
library(dplyr)
library(Matrix)
library(lme4)
library(ggeffects)
library(ggplot2)
```

### loading and cleaning data
```{r}
setwd("~/GitHub/Conspecific-Predator-Settlement-Cue")
data <- read.csv2(file="Experiment 05-2022[repeat study].csv", sep=",")
data <- select(data, -settled_10hr, -unattached_10hr, -settled_20hr, -unattached_20hr)
colnames(data)[5] <- 'Settled'
colnames(data)[6] <- 'Unattached'
data$Larvae.batch = as.factor(data$Larvae.batch)
```

### Calculate response variable from input data
```{r}
mult_s <- rep(1:nrow(data), data[, 'Settled'])
mult_u <- rep(1:nrow(data), data[, 'Unattached'])
data_s <- data[mult_s,]
data_s[, 'Settled'] <- 1
data_s <- data_s[, !(names(data_s) %in% c('Unattached'))]
data_u <- data[mult_u,]
data_u[, 'Unattached'] <- 0
data_u <- data_u[, !(names(data_u) %in% c('Settled'))]
colnames(data_u)[5] <- 'Settled'
data <- rbind(data_s, data_u)
```

### Adding binary predictor values
```{r}
data['Shell'] <- data['Cue']
data['conspecific_cue'] <- data['Cue']
data['predator_cue'] <- data['Cue']
data$Shell <- ifelse(grepl("conspecific shell", data$Shell), TRUE, FALSE)
data$conspecific_cue <- ifelse(grepl("conspecific cue", data$conspecific_cue), TRUE, FALSE)
data$predator_cue <- ifelse(grepl("predator cue", data$predator_cue), TRUE, FALSE)
data$Shell <-sub("TRUE", "untreated", data$Shell)
data$Shell <-sub("FALSE", "sterilized", data$Shell)
data$predator_cue <-sub("TRUE", "present", data$predator_cue)
data$predator_cue <-sub("FALSE", "absent", data$predator_cue)
data$conspecific_cue <-sub("TRUE", "present", data$conspecific_cue)
data$conspecific_cue <-sub("FALSE", "absent", data$conspecific_cue)
```

### Making the model 

```{r}
#model <-glmer(Settled ~ conspecific_cue * predator_cue + Shell + (1 | Larvae.age) + (1 | Larvae.batch), data = data, family = binomial)
#summary(model)

# Model with all first order interaction terms
model <-glmer(Settled ~ conspecific_cue + predator_cue + Shell + conspecific_cue:predator_cue + conspecific_cue:Shell + predator_cue:Shell + (1 | Larvae.age) + (1 | Larvae.batch), data = data, family = binomial)
summary(model)

m <- ggpredict(model, terms = c("conspecific_cue", "predator_cue"))
m2 <- ggpredict(model, terms = c("Shell", "conspecific_cue"))
m3 <- ggpredict(model, terms = c("Shell", "predator_cue"))
```

### plots 

```{r}
plot(m, connect.lines = TRUE) +
  labs(x = 'Conspecific Cue', 
       y= 'Larvae Settled (%)',
       title = "") +
  guides(color = guide_legend(title = "Predator Cue")) +
  scale_color_manual(breaks = c("absent", "present")
                     , labels= c("Absent", "Present"),
                     values = c("dodgerblue3", "orangered4")) +
  scale_y_continuous(labels= function(x) paste0(x*100), limits = c(0,1))


plot(m2, connect.lines = TRUE) +
  labs(x = 'Shell', 
       y= 'Larvae Settled (%)',
       title = "") +
  guides(color = guide_legend(title = "Conspecific Cue")) +
  scale_color_manual(breaks = c("absent", "present")
                     , labels= c("Absent", "Present"),
                     values = c("Khaki2", "dodgerblue3")) +
  scale_y_continuous(labels= function(x) paste0(x*100), limits = c(0,1)) 


plot(m3, connect.lines = TRUE) +
  labs(x = 'Shell', 
       y= 'Larvae Settled (%)',
       title = "") +
  guides(color = guide_legend(title = "Predator Cue")) +
  scale_color_manual(breaks = c("absent", "present")
                     , labels= c("Absent", "Present"),
                     values = c("Khaki2", "orangered4" )) +
  scale_y_continuous(labels= function(x) paste0(x*100), limits = c(0,1))
```


### Combined analysis May and August 2022

```{r}

data_may = data
colnames(data_may)
colnames(data_aug)

data_aug_new = data_aug[,-1] #remove "Date.started" variable
colnames(data_aug_new) = c("Larvae.age", "Larvae.batch", "Tray.Number", "Cue", "Settled", "Shell", "conspecific_cue", "predator_cue", "biofilm")
colnames(data_aug_new)
data_aug_new$Larvae.batch = as.factor(data_aug_new$Larvae.batch)
exp = rep("aug", nrow(data_aug_new))
data_aug_new = cbind(data_aug_new, exp)

biofilm = rep("absent", nrow(data_may))
data_may_new = cbind(data_may, biofilm)
exp = rep("may", nrow(data_may_new))
data_may_new = cbind(data_may_new, exp)

levels(data_aug_new$Larvae.batch) = c("3", "4")

data_combined = rbind(data_may_new, data_aug_new)

# Model with all first order interaction terms
model <-glmer(Settled ~ conspecific_cue + predator_cue + Shell + conspecific_cue:predator_cue + conspecific_cue:Shell + predator_cue:Shell + (1 | Larvae.age) + (1 | Larvae.batch) + (1 | biofilm) + (1 | exp), data = data_combined, family = binomial)
summary(model)

m <- ggpredict(model, terms = c("conspecific_cue", "predator_cue"))

plot(m, connect.lines = TRUE) +
  labs(x = 'Conspecific Cue', 
       y= 'Larvae Settled (%)',
       title = "") +
  guides(color = guide_legend(title = "Predator Cue")) +
  scale_color_manual(breaks = c("absent", "present")
                     , labels= c("Absent", "Present"),
                     values = c("dodgerblue3", "orangered4")) +
  scale_y_continuous(labels= function(x) paste0(x*100), limits = c(0,1))


# Post-hoc tests
data1 = data_combined[data_combined$conspecific_cue %in% c("present"),]
data1 = data_combined[data_combined$biofilm %in% c("absent"),]

model <- glmer(Settled ~ predator_cue + Shell + predator_cue:Shell + (1|biofilm) + (1|Larvae.age) + (1|Larvae.batch) + (1|exp), data = data1, family = binomial)
summary(model)

m <- ggpredict(model, terms = c("predator_cue"))


plot(m, connect.lines = TRUE) + 
  labs(x = 'Predator Cue', 
       y= 'Larvae Settled (%)',
       title = "") +
scale_y_continuous(labels= function(x) paste0(x*100), limits = c(0,.5)) 

```