---
title: "Cue interactions 08-2022"
author: "Sarah"
date: '2023-03-29'
output: html_document
---



loading packages 

```{r}
library(dplyr)
library(Matrix)
library(lme4)
library(ggeffects)
library(ggplot2)
library(DHARMa)
```

### loading and cleaning data 

```{r}
setwd("~/GitHub/Conspecific-Predator-Settlement-Cue")
data <- read.csv2(file="Cue interactions 08-2022.csv", sep=",")
colnames(data)[4] <- 'Well_Number'
colnames(data)[2] <- 'Age'
colnames(data)[3] <- 'Batch'
colnames(data)[5] <- 'Cue'
colnames(data)[6] <- 'Settled'
colnames(data)[7] <- 'Unattached'
data[, 'Cue'] <- as.factor(data[, 'Cue'])
```

### Calculate response variable from input data

```{r}
mult_s <- rep(1:nrow(data), data[, 'Settled'])
mult_u <- rep(1:nrow(data), data[, 'Unattached'])
data_s <- data[mult_s,]
data_s[, 'Settled'] <- 1
data_s <- data_s[, !(names(data_s) %in% c('Unattached'))]
data_u <- data[mult_u,]
data_u[, 'Unattached'] <- 0
data_u <- data_u[, !(names(data_u) %in% c('Settled'))]
colnames(data_u)[6] <- 'Settled'
data <- rbind(data_s, data_u)
```

### Adding binary predictor values
```{r}
data['Shell'] <- data['Cue']
data['conspecific_cue'] <- data['Cue']
data['predator_cue'] <- data['Cue']
data['biofilm'] <- data['Cue']
data$Shell <- ifelse(grepl("conspecific shell", data$Shell), TRUE, FALSE)
data$conspecific_cue <- ifelse(grepl("conspecific cue", data$conspecific_cue), TRUE, FALSE)
data$predator_cue <- ifelse(grepl("predator cue", data$predator_cue), TRUE, FALSE)
data$biofilm <- ifelse(grepl("biofilm", data$biofilm), TRUE, FALSE)
data$biofilm <-sub("TRUE", "present", data$biofilm)
data$biofilm <-sub("FALSE", "absent", data$biofilm)
data$Shell <-sub("TRUE", "untreated", data$Shell)
data$Shell <-sub("FALSE", "sterilized", data$Shell)
data$predator_cue <-sub("TRUE", "present", data$predator_cue)
data$predator_cue <-sub("FALSE", "absent", data$predator_cue)
data$conspecific_cue <-sub("TRUE", "present", data$conspecific_cue)
data$conspecific_cue <-sub("FALSE", "absent", data$conspecific_cue)
```

### Making the model 
```{r}
#model <- glmer(Settled ~ conspecific_cue * predator_cue + Shell +  biofilm + (1 | Batch) + (1 | Age), data = data, family = binomial)
#summary(model)

# Model with all first order interaction terms
model <- glmer(Settled ~ conspecific_cue + predator_cue + Shell +  biofilm + conspecific_cue:predator_cue + conspecific_cue:Shell + conspecific_cue:biofilm + predator_cue:Shell + predator_cue:biofilm + Shell:biofilm + (1 | Batch) + (1 | Age), data = data, family = binomial)
summary(model)
```

Testing model assumptions

```{r}
testDispersion(model)
simulationOutput <- simulateResiduals(fittedModel = model, plot = F)
plot(simulationOutput)
```

### plots
```{r}
m <- ggpredict(model, terms = c("conspecific_cue", "predator_cue"))
m2 <- ggpredict(model, terms = c("Shell", "conspecific_cue"))
m3 <-ggpredict(model, terms = c("Shell", "biofilm"))
m4 <-ggpredict(model, terms = c("biofilm", "conspecific_cue"))
m5 <-ggpredict(model, terms = c("Shell", "predator_cue"))
m6 <-ggpredict(model, terms = c("biofilm", "predator_cue"))

plot(m) + 
  labs(x = 'Conspecific Cue', 
       y= 'Larvae Settled (%)',
       title = "") +
  guides(color = guide_legend(title = "Predator Cue")) +
  scale_color_manual(breaks = c("absent", "present")
                     , labels= c("Absent", "Present"),
                     values = c("dodgerblue3", "orangered4"))+
scale_y_continuous(labels= function(x) paste0(x*100), limits = c(0,.5)) 


plot(m2) + 
  labs(x = 'Shell', 
       y= 'Larvae Settled (%)',
       title = "") +
  guides(color = guide_legend(title = "Conspecific Cue")) +
  scale_color_manual(breaks = c("absent", "present")
                     , labels= c("Absent", "Present"),
                     values = c("Khaki2", "dodgerblue3"))+
  scale_y_continuous(labels= function(x) paste0(x*100), limits = c(0,1)) 


plot(m3) +
  labs(x = "Shell", 
       y= 'Larvae Settled (%)',
       title = "") +
  guides(color = guide_legend(title = 'Biofilm')) +
  scale_color_manual(breaks = c("absent", "present")
                     , labels= c("Absent", "Present"),
                     values = c("Khaki2", "chartreuse4")) +
  scale_y_continuous(labels= function(x) paste0(x*100), limits = c(0,1))  


plot(m4) +
  labs(x = 'Conspecific Cue', 
       y= 'Larvae Settled (%)',
       title = "") +
  guides(color = guide_legend(title = "Biofilm")) +
  scale_color_manual(breaks = c("absent", "present")
                     , labels= c("Absent", "Present"),
                     values = c("dodgerblue3", "chartreuse4")) +
  scale_y_continuous(labels= function(x) paste0(x*100), limits = c(0,1)) 

plot(m5) +
  labs(x = 'Shell', 
       y= 'Larvae Settled (%)',
       title = "") +
  guides(color = guide_legend(title = "Predator Cue")) +
  scale_color_manual(breaks = c("absent", "present")
                     , labels= c("Absent", "Present"),
                     values = c("Khaki2", "orangered4"))+
  scale_y_continuous(labels= function(x) paste0(x*100), limits = c(0,1)) 



plot(m6) +
  labs(x = 'Biofilm', 
       y= 'Larvae Settled (%)',
       title = "") +
  guides(color = guide_legend(title = "Predator Cue")) +
  scale_color_manual(breaks = c("absent", "present")
                     , labels= c("Absent", "Present"),
                     values = c("chartreuse4", "orangered4"))+
  scale_y_continuous(labels= function(x) paste0(x*100), limits = c(0,1))
```

### graph with all cues 
```{r}
levels(data$Cue) <- c("B-CC-CS", "B-CC-PC-CS", "B-CC-PC-SS", "B-CC-SS", "B-CS", "B-PC-CS", "B-PC-SS", "B-SS", "CC-CS", "CC-PC-CS", "CC-PC-SS", "CC-SS", "CS", "PC-CS", "PC-SS", "SS")
model3 <- glmer(Settled ~ Cue + (1 | Batch) + (1 | Age), data = data, family = binomial)
m0<- ggpredict(model3, terms = ('Cue'))
plot(m0)
```
